// examples/vite-react/src/features/checkout/public/checkout-page.tsx
import { useState, useSyncExternalStore } from "react";
import {
  cartTotal,
  getCartItems,
  subscribeCart,
} from "@/services/cart/public/cart";
import { formatCurrency } from "@/shared/lib/format-currency";
import { Button } from "@/shared/ui/button";
import { Card } from "@/shared/ui/card";
import {
  getShippingLabel,
  getShippingMethod,
  type ShippingMethod,
  setShippingMethod,
  subscribeCheckout,
} from "../checkout.store";
import "./checkout-page.css";

export const CheckoutPage = () => {
  const items = useSyncExternalStore(subscribeCart, getCartItems);
  const shipping = useSyncExternalStore(subscribeCheckout, getShippingMethod);
  const [paid, setPaid] = useState(false);
  const total = cartTotal();

  const handlePay = () => {
    setPaid(true);
  };

  return (
    <section aria-labelledby="checkout-heading">
      <header>
        <h2 id="checkout-heading">Checkout</h2>
        <p>Review your cart and complete payment.</p>
      </header>

      <Card className="checkout-cart">
        <h3>Cart</h3>
        {items.length === 0 ? (
          <p>Your cart is empty. Add items from the catalog.</p>
        ) : (
          <ul>
            {items.map((item) => (
              <li key={item.id}>
                <span>{item.name}</span>
                <span>{formatCurrency(item.price)}</span>
              </li>
            ))}
          </ul>
        )}
        <div className="checkout-summary">
          <p>
            <strong>Items:</strong> {items.length}
          </p>
          <p>
            <strong>Total:</strong> {formatCurrency(total)}
          </p>
        </div>
      </Card>

      <fieldset>
        <legend>Shipping</legend>
        {(
          ["standard", "express"] as const satisfies readonly ShippingMethod[]
        ).map((method) => (
          <label key={method}>
            <input
              checked={shipping === method}
              name="shipping"
              onChange={() => setShippingMethod(method)}
              type="radio"
              value={method}
            />
            {getShippingLabel(method)}
          </label>
        ))}
      </fieldset>

      <footer className="checkout-footer">
        <Button
          disabled={paid || items.length === 0}
          label={paid ? "Paid" : `Pay ${formatCurrency(total)}`}
          onClick={handlePay}
        />
        {paid ? (
          <p className="checkout-status" role="status">
            Payment received. Thank you!
          </p>
        ) : null}
      </footer>
    </section>
  );
};

// examples/vue-vite/src/features/checkout/public/checkout-page.vue
<script setup lang="ts">
import { formatCurrency } from "@/shared/lib/format-currency";
import Button from "@/shared/ui/button.vue";
import Card from "@/shared/ui/card.vue";
import { checkoutStore } from "../checkout.store";
import { useCheckout } from "../use-checkout";

const { getShippingLabel, items, setPaid, setShippingMethod, total } =
	useCheckout();

const shippingMethods = ["standard", "express"] as const;

function handlePay(): void {
	setPaid(true);
}
</script>

<template>
  <section class="checkout" aria-labelledby="checkout-heading">
    <header>
      <h2 id="checkout-heading">Checkout</h2>
      <p>Review your cart and complete payment.</p>
    </header>

    <Card>
      <h3>Cart</h3>
      <p v-if="items.length === 0">Your cart is empty. Add items from the catalog.</p>
      <ul v-else class="checkout-items">
        <li v-for="item in items" :key="item.id">
          <span>{{ item.name }}</span>
          <span>{{ formatCurrency(item.price) }}</span>
        </li>
      </ul>
      <p><strong>Items:</strong> {{ items.length }}</p>
      <p><strong>Total:</strong> {{ formatCurrency(total) }}</p>
    </Card>

    <fieldset class="checkout-shipping">
      <legend>Shipping</legend>
      <label v-for="method in shippingMethods" :key="method">
        <input
          type="radio"
          name="shipping"
          :value="method"
          :checked="checkoutStore.shippingMethod === method"
          @change="setShippingMethod(method)"
        />
        {{ getShippingLabel(method) }}
      </label>
    </fieldset>

    <footer>
      <Button
        :disabled="checkoutStore.paid || items.length === 0"
        :label="checkoutStore.paid ? 'Paid' : `Pay ${formatCurrency(total)}`"
        :variant="checkoutStore.paid ? 'secondary' : 'primary'"
        @click="handlePay"
      />
      <p v-if="checkoutStore.paid" role="status">Payment received. Thank you!</p>
    </footer>
  </section>
</template>

<style scoped>
.checkout-items {
	margin: 0.75rem 0;
	padding: 0;
	list-style: none;
}

.checkout-items li {
	display: flex;
	justify-content: space-between;
	gap: 1rem;
	padding: 0.25rem 0;
}

.checkout-shipping {
	margin: 1rem 0;
	padding: 0.75rem;
	border: 1px solid var(--color-border);
	border-radius: 0.375rem;
}

.checkout-shipping label {
	display: block;
	margin-top: 0.5rem;
}
</style>
