// examples/vue-vite/src/features/catalog/public/catalog-page.vue
<script setup lang="ts">
import { formatCurrency } from "@/shared/lib/format-currency";
import Badge from "@/shared/ui/badge.vue";
import Button from "@/shared/ui/button.vue";
import Card from "@/shared/ui/card.vue";
import Input from "@/shared/ui/input.vue";
import { catalogStore } from "../catalog.store";
import { useCatalog } from "../use-catalog";
import { useCatalogCart } from "../use-catalog-cart";
import { useCatalogSearch } from "../use-catalog-search";

const emit = defineEmits<{
	addedToCart: [productName: string];
}>();

const { setCategory } = useCatalog();
const { visibleProducts } = useCatalogSearch();
const { addToCart, cartItems } = useCatalogCart();

const categories = [
	{ id: "all" as const, label: "All" },
	{ id: "books" as const, label: "Books" },
	{ id: "merch" as const, label: "Merch" },
];

function handleAdd(product: (typeof visibleProducts.value)[number]): void {
	if (addToCart(product)) {
		emit("addedToCart", product.name);
	}
}

function isInCart(productId: string): boolean {
	return cartItems.value.some((item) => item.id === productId);
}
</script>

<template>
  <section class="catalog" aria-labelledby="catalog-heading">
    <header>
      <h2 id="catalog-heading">Catalog</h2>
      <p>Browse products and add them to the cart service.</p>
    </header>

    <div :class="$style.toolbar">
      <Input
        id="catalog-search"
        v-model="catalogStore.searchQuery"
        label="Search"
        placeholder="Filter by name…"
      />

      <div :class="$style.filters" aria-label="Category" role="group">
        <button
          v-for="{ id, label } in categories"
          :key="id"
          type="button"
          :class="catalogStore.category === id ? $style.filterActive : $style.filter"
          :aria-pressed="catalogStore.category === id"
          @click="setCategory(id)"
        >
          {{ label }}
        </button>
      </div>
    </div>

    <ul :class="$style.grid">
      <li v-for="product in visibleProducts" :key="product.id">
        <Card>
          <header :class="$style.cardHeader">
            <h3>{{ product.name }}</h3>
            <Badge variant="accent">{{ product.category }}</Badge>
          </header>
          <p :class="$style.price">{{ formatCurrency(product.price) }}</p>
          <Button
            :label="isInCart(product.id) ? 'In cart' : 'Add to cart'"
            :variant="isInCart(product.id) ? 'secondary' : 'primary'"
            @click="handleAdd(product)"
          />
        </Card>
      </li>
    </ul>

    <p v-if="visibleProducts.length === 0" role="status">
      No products match your filters.
    </p>
  </section>
</template>

<style scoped>
.catalog header p {
	margin: 0.25rem 0 0;
	color: var(--color-muted);
}
</style>

<style module src="./catalog-page.module.css"></style>

// examples/sveltekit-routes/src/features/catalog/public/catalog-page.svelte
<script lang="ts">
import { addCartItem } from "@/services/cart/public/cart";
import { formatCurrency } from "@/shared/lib/format-currency";
import Button from "@/shared/ui/button.svelte";
import Card from "@/shared/ui/card.svelte";
import { catalogStore, setCatalogSearchQuery } from "../catalog.store";

const products = [
  { id: "tea", name: "Green tea", price: 4.5 },
  { id: "mug", name: "Ceramic mug", price: 12 },
  { id: "honey", name: "Wild honey", price: 8 },
] as const;

function handleSearchInput(event: Event) {
  const target = event.currentTarget as HTMLInputElement;
  setCatalogSearchQuery(target.value);
}

function addProduct(product: (typeof products)[number]) {
  addCartItem(product);
}
</script>

<section class="catalog" id="catalog">
  <h2>Catalog</h2>
  <label class="search">
    <span class="search-label">Search</span>
    <input
      class="search-input"
      oninput={handleSearchInput}
      placeholder="Filter products…"
      type="search"
      value={$catalogStore.searchQuery}
    />
  </label>

  <ul class="product-list">
    {#each products.filter((product) => product.name
          .toLowerCase()
          .includes($catalogStore.searchQuery.trim().toLowerCase())) as product (product.id)}
      <li>
        <Card title={product.name}>
          <p class="price">{formatCurrency(product.price)}</p>
          <Button
            label="Add to cart"
            onclick={() => {
              addProduct(product);
            }}
          />
        </Card>
      </li>
    {/each}
  </ul>
</section>

<style>
  .catalog {
    display: grid;
    gap: 1rem;
  }

  .search {
    display: grid;
    gap: 0.375rem;
  }

  .search-label {
    color: var(--color-muted);
    font-size: 0.875rem;
  }

  .search-input {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    color: var(--color-text);
    font: inherit;
    padding: 0.5rem 0.75rem;
  }

  .search-input:focus {
    border-color: var(--color-accent);
    outline: 2px solid color-mix(in srgb, var(--color-accent) 25%, transparent);
    outline-offset: 1px;
  }

  .product-list {
    display: grid;
    gap: 0.75rem;
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .price {
    font-weight: 600;
    margin: 0 0 0.75rem;
  }
</style>
